[rpc]
process_name = "GeometryDash"
refresh_rate = 1
client_id = 704721375050334300

[rpc.editor]
details = "Editing level"
state = "{level_name} ({object_count} objects)"

[rpc.level]
details = "{level_name} ({level_type}) <{gamemode}>"
state = "by {level_creator} ({mode} {percent}%, best {best_normal}%/{best_practice}%)"
small_text = "{level_stars}* {level_difficulty} (ID: {level_id})"
percent_precision = 1

[rpc.scene]
main = "Idle"
select = "Selecting level"
editor_or_level = "Watching level info"
search = "Searching levels"
leaderboard = "Browsing leaderboards"
online = "Online"
official_levels = "Selecting official level"
official_level = "Playing official level"

[rpc.difficulty]
na = "N/A"
auto = "Auto"
easy = "Easy"
normal = "Normal"
hard = "Hard"
harder = "Harder"
insane = "Insane"
demon = "Demon"
easy_demon = "Easy Demon"
medium_demon = "Medium Demon"
hard_demon = "Hard Demon"
insane_demon = "Insane Demon"
extreme_demon = "Extreme Demon"

[rpc.gamemode]
cube = "Cube"
ship = "Ship"
ball = "Ball"
ufo = "UFO"
wave = "Wave"
robot = "Robot"
spider = "Spider"

[rpc.level_type]
null = "null"
official = "official"
editor = "editor"
saved = "saved"
online = "online"

[rpc.mode]
normal = "normal"
practice = "practice"
